server:
  port: 8080

spring:
  application:
    name: ctpop-backend
  redis:
    host: localhost
    port: 6379
    # Redis 연결 설정
    connect-timeout: 2000
    client-name: ctpop-client
    lettuce:
      shutdown-timeout: 0ms

app:
  twilio:
    account-sid: ${TWILIO_SID}
    auth-token: ${TWILIO_TOKEN}
    verify-sid: ${TWILIO_VERIFY_SID}
  jwt:
    secret: ${JWT_SECRET:devSecretKey123456789012345678901234567890}
    expiration-ms: 1800000      # 30 minutes
    refresh-expiration-ms: 2592000000  # 30 days

# Swagger/OpenAPI 설정
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs 